### PR TITLE
Replace anonymous types with lambdas and method references

### PR DESCRIPTION
**Pull request by gsmith85**
Project wide change to adopt Java 8 language feature.

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Launched the CI. All refactorings look good to me, the code complexity is definitely lower. Just do not get me started on `throwUnchecked()` but it was there even before the Pull request :)

**Comment by oleg-nenashev** [comment]
@gsmith85 could you please apply spotless to the PR?

**Comment by pks-1981** [comment]
Hi @tomakehurst @oleg-nenashev 
I may update my MR's (https://github.com/wiremock/wiremock/pull/2120, https://github.com/wiremock/wiremock/pull/2121), when you merge this.

**Review by oleg-nenashev — APPROVED** [review]
Leaving the merge to @tomakehurst

**Comment by tomakehurst** [comment]
I think this has been rendered redundant by https://github.com/wiremock/wiremock/pull/2120 and https://github.com/wiremock/wiremock/pull/2121.

Is there anything additional this brings now that these are merged?

**Pull request closed without merging**
