### PR TITLE
Fixed Allow/Deny Proxy targets for DomainNameWildCard

### PR DESCRIPTION
**Pull request by numacanedo**
## Description
[ProxyResponseRenderer:151](https://github.com/numacanedo/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java#L151) is now calling `targetAddressRules.isAllowed(InetAddress addres)`
```java
  public boolean isAllowed(InetAddress address) {
    return allowed.stream().anyMatch(rule -> rule.isIncluded(testValue(rule, address)))
        && denied.stream().noneMatch(rule -> rule.isIncluded(testValue(rule, address)));
  }
```

By directly providing the inet address, each allowed/denied rule[NetworkAddressRules:41](https://github.com/numacanedo/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/common/NetworkAddressRules.java#L41) can be evaluated to determine if the `address.getHostName()` or `address.getHostAddress()` should be used.
```java
  private String testValue(NetworkAddressRange rule, InetAddress address) {
    return rule.isDomainNameWildCard() ? address.getHostName() : address.getHostAddress();
  }
```

To help this determination [NetworkAddressRange.isDomainNameWildCard()](https://github.com/numacanedo/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/common/NetworkAddressRange.java#L46C1-L48C4) method is added.
```java
  public boolean isDomainNameWildCard() {
    return this instanceof DomainNameWildcard;
  }
```
## Unit tests
Without this change this unit test will fail:
```java
  @Test
  void preventsProxyingToDeniedHostnamesAndProxyAllowedHostNames() {
    init(
        wireMockConfig()
            .limitProxyTargets(
                NetworkAddressRules.builder()
                    .allow("wiremock.org")
                    .allow("*.wiremock.org")
                    .deny("wiremock.io")
                    .build()));

    proxy.register(proxyAllTo("https://wiremock.org"));
    assertThat(testClient.get("/").statusCode(), is(200));

    proxy.register(proxyAllTo("https://www.wiremock.org"));
    assertThat(testClient.get("/").statusCode(), is(301));

    proxy.register(proxyAllTo("http://wiremock.io"));
    assertThat(
        testClient.get("/").content(),
        is("The target proxy address is denied in WireMock's configuration."));
  }
```

## References
[Issue 2248](https://github.com/wiremock/wiremock/issues/2248)

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Thanks @numacanedo! While this change is totally reasonable, it breaks binary compatibility of `NetworkAddressRules`. I suggest restoring the  `isAllowed(String)` method, you can use https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/InetAddress.html#getByName(java.lang.String) for that. Then, all the changes in the tests could be reverted too, introducing so much mocking does not look justified for the change

**Comment by numacanedo** [comment]
@oleg-nenashev Restored isAllowed(String) and original tests.

**Comment by oleg-nenashev** [comment]
Sorry @numacanedo I missed the update because of vacation.
Would it be possible to pull in the current `master` branch?

**Comment by numacanedo** [comment]
Hi @oleg-nenashev , sure

**Comment by oleg-nenashev** [comment]
Hello @numacanedo , For your information, we have just released a security fix that also incorportates a similar patch: https://github.com/wiremock/wiremock/releases/tag/3.0.3 . You are credited in the release and you should have received an invite to be added to advisory as a finder too. I will close this PR to avoid confusion

**Pull request closed without merging**
