### PR TITLE
Allow matchesJsonSchema to be supplied as a json object.

### PR DESCRIPTION
**Pull request by kyle-winkelman**
https://wiremock.org/docs/request-matching/#json-schema shows an example of using the `matchesJsonSchema` with an escaped json string:
```json
{
  "request" : {
    "urlPath" : "/schema-match",
    "method" : "POST",
    "bodyPatterns" : [ {
      "matchesJsonSchema" : "{\n  \"type\": \"object\",\n  \"required\": [\n    \"name\"\n  ],\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\"\n    },\n    \"tag\": {\n      \"type\": \"string\"\n    }\n  }\n}",
      "schemaVersion" : "V202012"
    } ]
  },
  "response" : {
    "status" : 200
  }
}
```

This PR would allow us to supply a json object (similar to `equalToJson`). For example:
```json
{
  "request" : {
    "urlPath" : "/schema-match",
    "method" : "POST",
    "bodyPatterns" : [ {
      "matchesJsonSchema" : {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "tag": {
            "type": "string"
          }
        }
      }
    } ]
  },
  "response" : {
    "status" : 200
  }
}
```

## References

- Will link wiremock.org PR for update to documentation if this PR is accepted

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Review by dieppa — APPROVED** [review]
Thanks a lot! It looks good! From your previous comment I assume this will complemented with a PR in the documentation project.

Thanks!

**Comment by dieppa** [comment]
Hello @kyle-winkelman , once again thanks for your contribution!

Are you planning to provide the documentation on this? There is no pressure, but just for us to plan the workload.

Thanks in advance!

**Comment by kyle-winkelman** [comment]
https://github.com/wiremock/wiremock.org/pull/252
Yes, I mentioned this PR, but didn't explicitly link it back here.

**Comment by dieppa** [comment]
Ah, Ok.Thanks!

**Pull request merged**
