### PR TITLE
Provide separate Jetty 10 version

### PR DESCRIPTION
**Pull request by henrik242**
This is needed when using other dependencies with a Jetty 10 dependency (such as Solr 9.2) together with Wiremock.

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
So far this version is not really separate. Gradle definition needs to be changed to build both artifacts. Or, if @tomakehurst sees it as important use-cases, it could be maintained in a branch. Maybe switching to https://github.com/wiremock/wiremock-testcontainers-java is actually a better solution for this case

**Comment by tomakehurst** [comment]
I'm still thinking Docker or standalone are better options than us having to maintain both Jetty 10 and 11 versions.

**Comment by oleg-nenashev** [comment]
Closing the pull request based on the discussion above. The pull request would need a significant rework to have it compatible with the 3.x extensions rework anyway

**Comment by henrik242** [comment]
In case anyone needs it, here's an updated jetty10 fork of wiremock 3.3.1: https://github.com/henrik242/wiremock/tree/3.3.1.jetty10

**Comment by oleg-nenashev** [comment]
Nice @henrik242! If you'd like to document the fork as a temporary solution somewhere on the website, it might be helpful. Meanwhile I will refactor this ticket a bit for better discoverability

**Comment by henrik242** [comment]
@oleg-nenashev Sure, any suggestions to where it could be documented?

**Comment by henrik242** [comment]
Here's the jetty10 fork of 3.4.1: https://github.com/henrik242/wiremock/tree/3.4.1.jetty10

**Comment by tomakehurst** [comment]
@henrik242 we've started working towards separate JARs for different Jetty versions. Might be a good pattern to copy for 10 also:
https://github.com/wiremock/wiremock/tree/reta-issue-2395-jetty-12

**Pull request closed without merging**
