### PR TITLE
Adding admin route for resetting a specific scenario by name

### PR DESCRIPTION
**Pull request by matthewwilson**
This PR adds a new admin endpoint:

`POST /scenarios/reset/{scenarioName}`

This will reset the state of the given scenario name.

I believe this will fix issue #847 as well as suit a use case for our own project.

### CODE REVIEW

**Comment by matthewwilson** [comment]
@tomakehurst not sure why travis is failing, tests are passing locally for me. Am I missing a step before I should have created the PR?

**Comment by matthewwilson** [comment]
Looks like travis is failing because:

java.lang.IllegalArgumentException: resource swagger/wiremock-admin-api.json not found.

Is this file supposed to be autogenerated?

**Comment by matthewwilson** [comment]
Got the build passing however not sure it is the best solution. The issue was that the `generateAPIDocs` task was not running before `test`. I tried making `test` depend on `generateAPIDocs` however that didn't fix it. Last resort was to move the tasks out of the subtasks project and call `generateAPIDocs` before `test` in the travis file.

**Comment by szekar1** [comment]
Hi @tomakehurst @matthewwilson,
any plans of including this in upcoming releases?

Best Regards,
Karol

**Comment by FrankSandou** [comment]
Hi ,@tomakehurst @matthewwilson,
Could you add this  in next release?i need this functional

**Comment by FrankSandou** [comment]
> @FrankSandou there's a workaround for this which is to create a stub (mapped to a URL that's not in the API you're mocking) that resets the relevant scenario when you request it.

I need for  one scenario reset state , not for all , could you add this feature in release (hotfix) @tomakehurst 

Best regards, Frank

**Comment by tomakehurst** [comment]
The workaround is for resetting single scenario state.

**Comment by FrankSandou** [comment]
> The workaround is for resetting single scenario state.
@tomakehurst 
Yes, i need this , could you merge in master?

Best regards, Frank

**Comment by tomakehurst** [comment]
No, I mean the workaround I described works for a single scenario. You don't need this PR to be merged to be able to set a single scenario's state - just create a stub that does that for you.

**Comment by FrankSandou** [comment]
> No, I mean the workaround I described works for a single scenario. You don't need this PR to be merged to be able to set a single scenario's state - just create a stub that does that for you.

Hmm, how i can reset one state for one  scenario, if i have 5 scenarios with different states?, only this fix, please merge this , i need this very , and wait  for this api routing ...

**Comment by tomakehurst** [comment]
I'm sorry, but I'm not planning to do a WireMock release in the timeframe you're hoping for.

I suggest you configure a stub for each scenario you want to reset and the make a request that matches the appropriate stub when you want to perform the reset.

**Comment by FrankSandou** [comment]
> I'm sorry, but I'm not planning to do a WireMock release in the timeframe you're hoping for.
> 
> I suggest you configure a stub for each scenario you want to reset and the make a request that matches the appropriate stub when you want to perform the reset.



> I'm sorry, but I'm not planning to do a WireMock release in the timeframe you're hoping for.
> 
@tomakehurst  are you planned release in next year  January  or February ?  
I hope and wait  for  this feature in next release .
Best regards, Frank

**Comment by matthewwilson** [comment]
@FrankSandou it looks like the workaround suggested by @tomakehurst will work. 

Let's say you have a stub that is in a state called "state-1" and you want to reset it back to "started". Simply define another stub that exists purely to reset the state. E.g.

```
{
    "scenarioName": "My Scenario",
    "requiredScenarioState": "state-1",
    "newScenarioState": "started",
    "request": {
        "method": "POST",
        "url": "/state-management/reset-my-scenario"
    },
    "response": {
        "status": 200
    }
}

```

**Pull request closed without merging**
