### PR TITLE
Replace com.google.common.base.Function (partly)

### PR DESCRIPTION
**Pull request by pks-1981**
Replace com.google.common.base.Function

## References

- https://github.com/wiremock/wiremock/issues/2111

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Comment by tomakehurst** [comment]
Sorry fixed it, if you want to rebase

**Comment by timtebeek** [comment]
Quick reminder that there's this recipe to broadly replace guava:
https://docs.openrewrite.org/recipes/java/migrate/guava/noguava

And this recipe to specifically replace function:
https://docs.openrewrite.org/recipes/java/migrate/guava/preferjavautilfunction

Could be worth exploring either for this pull request.

**Comment by pks-1981** [comment]
> Quick reminder that there's this recipe to broadly replace guava: https://docs.openrewrite.org/recipes/java/migrate/guava/noguava
> 
> And this recipe to specifically replace function: https://docs.openrewrite.org/recipes/java/migrate/guava/preferjavautilfunction
> 
> Could be worth exploring either for this pull request.



> Quick reminder that there's this recipe to broadly replace guava: https://docs.openrewrite.org/recipes/java/migrate/guava/noguava
> 
> And this recipe to specifically replace function: https://docs.openrewrite.org/recipes/java/migrate/guava/preferjavautilfunction
> 
> Could be worth exploring either for this pull request.

Hello
Do you mean make "com.google.common.base.Joiner" apart from this MR?
It's to small for MR, IMHO...

**Comment by timtebeek** [comment]
> Hello Do you mean make "com.google.common.base.Joiner" apart from this MR? It's to small for MR, IMHO...

I mean to say that some of the changes you're making here manually can also be made through automation. That might mean you can accomplish more in the same time.

Here's another recipe that creates some of the same changes I see you make here:
https://docs.openrewrite.org/recipes/java/cleanup/uselambdaforfunctionalinterface

**Comment by pks-1981** [comment]
@tomakehurst @timtebeek 
Please look at StringValuePatternTest.
I can remake it without com.google.common.base.Function. But in my opinion it does nothing ... or I'm debugging incorrectly)))

**Comment by pks-1981** [comment]
@tomakehurst @timtebeek 
Hello. I can continue getting rid of "com.google.common.base.Predicate" here or create a new MR.
What's are You prefer?)))

**Pull request merged**
