### PR TITLE
proxy request fix

### PR DESCRIPTION
**Pull request by AntonDyukarev**
fix request entity setting for any request methods

### CODE REVIEW

**Comment by kermek** [comment]
@tomakehurst could you please review this PR, this issue affects our tests.

**Comment by tomakehurst** [comment]
@AntonDyukarev please could you add a test case?

**Comment by AntonDyukarev** [comment]
@tomakehurst i'll try=)
@kermek can you list some broken tests please

**Comment by kermek** [comment]
@tomakehurst @AntonDyukarev any news on this one?

**Comment by AntonDyukarev** [comment]
> @tomakehurst @AntonDyukarev any news on this one?

Hi! I waiting for your answers about my tests

**Comment by tomakehurst** [comment]
@AntonDyukarev can you push your tests so I can take a look at the issue you encountered?

**Comment by AntonDyukarev** [comment]
@tomakehurst They already pushed

**Comment by kermek** [comment]
@tomakehurst any news on this one?

**Comment by kermek** [comment]
@tomakehurst could you please look at this PR?

**Pull request merged**
