### PR TITLE
2197 | added field "mappings" to StubMapping and its processing if it exists

### LINKED ISSUE #2197: Support multiple mappings files when remotely loading stubs from the filesystem
### Proposal

While it's possible at present to push a collection of stub mappings from the file system to a remote instance via `wireMock.loadMappingsFrom("/my/path")` this only supports single stub mapping files, not the newer multiple mapping file format (with the `"mappings"` key at the root).

This would be desirable so that sets of related stubs can be combined into single files, without needing to merge the entire set into a single file for remote import.

### References

https://github.com/wiremock/wiremock/issues/1921

### PR DESCRIPTION
**Pull request by DjerohN**
This pull request adds field "mappings" to StubMapping class and processing to load() method of RemoteMappingsLoader class if present

## References

- Resolves #2197 issue in a simple way for now, because I don't know plans for 3.0 imports

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Comment by DjerohN** [comment]
@tomakehurst @oleg-nenashev

**Comment by tomakehurst** [comment]
This isn't the right approach - there's already `StubMappingCollection` for this purpose which is used when reading the `mappings` directory via `JsonFileMappingsSource`. I suggest we adapt `RemoteMappingsLoader` to work the same way.

**Comment by DjerohN** [comment]
Used `StubMappingCollection` as @tomakehurst  suggested

**Comment by tomakehurst** [comment]
Please could you run `./gradlew spotlessApply` and push the fixes?

**Comment by DjerohN** [comment]
Done

**Comment by tomakehurst** [comment]
Thanks!

**Pull request merged**
