### PR TITLE
Add mising schema properties

### PR DESCRIPTION
**Pull request by picimako**
## Changes
- Added the `scheme`, `host`, `port`, `customMatcher` and `multipartPatterns` request-pattern properties to the JSON schema.
- Added the `serveEventListeners` property to the stub-mapping JSON schema. This was introduced in 3.0.0-beta-11.

## References

None.

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [ ] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Thanks for catching! I guess we will need to also update https://github.com/wiremock/spec with these (and other missing?) fields

**Comment by picimako** [comment]
@oleg-nenashev When this is approved (and merged), I'm happy to add these to the *spec* repo as well.

**Comment by picimako** [comment]
@oleg-nenashev Sure, I'll collect them and list them in an issue.

**Review by oleg-nenashev — APPROVED** [review]
I will merge it to initiate the migration process

**Pull request merged**
