### PR TITLE
fix: introduce a slight delay given the 2-3 results is slightly flakey

### PR DESCRIPTION
**Pull request by SimonVerhoeven**
## References

Introduces a slight delay in the flakey test to hopefully avoid this in the future.

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] Recommended: If you participate in Hacktoberfest 2023, make sure you're [signed up](https://wiremock.org/events/hacktoberfest/) there and in the WireMock form 
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Uhm. It will make the test lesss flaky but I do not think it will fix the issue entirely. I suggest creating a follow-up github issue and adding a `FIXME` comment with a reference

**Comment by tomakehurst** [comment]
Please can you share some context on this?

I haven't noticed flakeyness in this test but if there is then it's probably an issue with the production code, and we should fix it rather than masking it with a delay.

**Comment by SimonVerhoeven** [comment]
@tomakehurst I haven't encountered it live yet, but I spotted the builds failing on it now and then:

https://github.com/wiremock/wiremock/actions/runs/6632467648/job/18018242892
https://github.com/wiremock/wiremock/actions/runs/6618946239/job/17989005366
https://github.com/wiremock/wiremock/actions/runs/6545788261/job/17774974937
https://github.com/wiremock/wiremock/actions/runs/6544477898/job/17771014388

**Comment by tomakehurst** [comment]
Actually, looking at this again I think this is a reasonable fix so I'll merge it. Might try dropping the delay values a bit after...

**Pull request merged**
