### PR TITLE
Bumping Handlebars library version to 4.3.1, #1990

### PR DESCRIPTION
**Pull request by lucasvc**
This fixes the issue #1990.

### CODE REVIEW

**Comment by james-bjss** [comment]
Is there a new release + container image with this in apart from the nightlies?

**Comment by kevag4** [comment]
Same question as @james-bjss . Is this commit reflected to a new version? Also wiremock-docker image seems NOT to contain this image

**Comment by tomakehurst** [comment]
Will be released in 2.35.0, which I'm going to try to cut today or tomorrow.

**Comment by pcgeng** [comment]
> Will be released in 2.35.0, which I'm going to try to cut today or tomorrow.

I can't wait to use the new version, thank you!

**Comment by pcgeng** [comment]
@tomakehurst will 2.35.0 be released in these two days?

**Comment by husnutapan** [comment]
Is there any update for this fix @tomakehurst

**Pull request merged**
