### PR TITLE
Introduced contender in the dynamic scenarios.

### PR DESCRIPTION
**Pull request by ioanngolovko**
Implemented the demo of dynamic scenarios.

[Sluck discussion](https://wiremock-community.slack.com/archives/C053Y3N34C8/p1689588297883109)

Special notes.

1. There is no caching with ttl for generated  dynamic cases now. Suggest using [caffeine](https://github.com/ben-manes/caffeine).
2. Not all the cases are tested now. But we have at least base concepts.
3. I don't know hot to do [this](https://github.com/ioanngolovko/wiremock/commit/fb38929d50dca64f37988c6954226d5c3be99f00#diff-0a56c3890aebfa812c8cdd9edf7dede3d1db31fdd3ea88090fa47f7402775d76R37) better and independent from transformers. Any ideas to make it clear?
4. I was only able to resolve dynamic key with a PathPattern due to simplicity. Maybe someone can suggest an option for UrlPattern ?

Any of your ideas are welcome.

## References

- https://github.com/wiremock/wiremock/issues/1142

## Submitter checklist

- [ ] The PR request is well described and justified, including the body and the references
- [ ] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [ ] Test coverage that demonstrates that the change works as expected
- [ ] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
> How about the new transformParameterResolvers?

I would probably call them `transformParameterProviders` to follow the general approach, but otherwise it is a reasonable addition to WireMock. It would technically allow to put the rest of the implementation to an extension, right? It might be a more natural fit to have this code inside https://github.com/wiremock/wiremock-extension-state, CC @dirkbolte 


I still need some time to review and answer questions from the PR title. Ultimately, we will need @tomakehurst to weight in on new extensions and code bits, but it is definitely a great start, thanks you!

**Comment by dirkbolte** [comment]
I'm not sure whether I grasped everything you want to cover.  https://github.com/wiremock/wiremock-extension-state should work together with scenarios, so you should be able to store everything you need to build dynamic responses in your scenarios. Glad if I can support you in making the extension more useful.

**Comment by ioanngolovko** [comment]
> I'm not sure whether I grasped everything you want to cover. https://github.com/wiremock/wiremock-extension-state should work together with scenarios, so you should be able to store everything you need to build dynamic responses in your scenarios. Glad if I can support you in making the extension more useful.

Hi. You can destroy this PR due to https://github.com/wiremock/wiremock-extension-state is able to manage complex cases.

**Comment by ioanngolovko** [comment]
https://github.com/wiremock/wiremock-extension-state is able to simulate complex scenarios with states. Therefore this PR is closed. Thank you all for participation.

**Pull request closed without merging**
